env:
  browser: true
  node: true
plugins:
  - prettier
  - react
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  brace-style: 2
  curly: 2
  dot-notation: 2
  id-length: 2
  no-console: 1
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-inner-declarations: 2
  no-lonely-if: 2
  no-magic-numbers:
    - 1
    - ignore:
        - -1
        - 0
        - 1
  no-shadow: 2
  no-unneeded-ternary: 2
  no-unused-expressions: 2
  no-unused-vars:
    - 2
    - args: none
  no-useless-return: 2
  no-var: 2
  one-var:
    - 2
    - never
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prettier/prettier:
    - 2
    - endOfLine: auto
  semi: 2
  sort-imports: 0
  sort-keys:
    - 2
    - asc
    - caseSensitive: false
      natural: true
  sort-vars: 2
